theme: jekyll-theme-slate
title: Wifi Lightbulb Classroom Soundmeter
description: Changing the color of a Wi-Fi smart lightbulb when the sound level in a classroom changes for classroom management!
show_downloads: true
