theme: jekyll-theme-slate
title: Wifi Lightbulb Classroom Soundmeter
description: Changing the color of a Wi-Fi smart lightbulb when the sound level in a classroom changes for classroom management!
show_downloads: true
github:
  zip_url: https://github.com/kevinl95/WiFi-Lightbulb-Classroom-Soundmeter/releases/download/1.1/wifi-lightbulb-classroom-soundmeter-win32-x64.zip
  tar_url: https://github.com/kevinl95/WiFi-Lightbulb-Classroom-Soundmeter/releases/download/1.1/wifi-lightbulb-classroom-soundmeter-win32-x64.tar.gz
